# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Unified Gibbs sampler for all three BFL variants
#'
#' Run one MCMC chain. Call from R once per chain with a different seed.
#' Pass \code{Y_known = integer(N)} and \code{Y_idx_r = rep(1L, N)} for the
#' no-partial-labels variant (no cause is observed, so the Y arguments are
#' never used).
#'
#' @param phi            Flattened phi array (column-major, dim N x C_max x M).
#' @param model_presence num_causes x M integer matrix; 1 = model active.
#' @param causes_r       1-indexed cause codes, length num_causes.
#' @param Y_known        Integer vector length N: 1 = cause observed, 0 = latent.
#'   Pass \code{integer(N)} for the no-partial variant.
#' @param Y_idx_r        Integer vector length N: 1-indexed cause index used
#'   where Y_known = 1. Pass \code{rep(1L, N)} for the no-partial variant.
#' @param N,C_max,M,num_causes Array dimensions.
#' @param n_iter         Total iterations (warmup + sampling).
#' @param n_warmup       Iterations to discard.
#' @param single_pi      TRUE = one pi for all observations (no_partial and
#'   balanced); FALSE = separate pi (unlabeled) and pi_O (labeled).
#' @param logistic_normal If TRUE, use N(0,1)->softmax prior with MH step.
#' @param mh_scale       Random-walk MH step-size (only used when logistic_normal=TRUE).
#'
#' @return List: pi [n_keep x num_causes], pi_O [n_keep x num_causes] (zeros
#'   when single_pi=TRUE), lambda [n_keep*num_causes*M],
#'   mh_accept_rate [num_causes] (NA when logistic_normal=FALSE).
#' @keywords internal
gibbs_bfl_cpp <- function(phi, model_presence, causes_r, Y_known, Y_idx_r, N, C_max, M, num_causes, n_iter, n_warmup, single_pi = TRUE, logistic_normal = FALSE, mh_scale = 0.5) {
    .Call(`_BFL_gibbs_bfl_cpp`, phi, model_presence, causes_r, Y_known, Y_idx_r, N, C_max, M, num_causes, n_iter, n_warmup, single_pi, logistic_normal, mh_scale)
}

#' Posterior predictive sampler (Rcpp)
#'
#' @param phi_vec    Flattened phi array [I, C, M] column-major.
#' @param lambda_vec Flattened lambda array [S, C, M] column-major.
#' @param pi_vec     Flattened pi matrix [S, C] column-major.
#' @param I,C,M,S   Dimensions.
#'
#' @return List: posterior_pred_Y_prob_mean [I x C], posterior_pred_Y [S x I].
#' @keywords internal
post_pred_sample_cpp <- function(phi_vec, lambda_vec, pi_vec, I, C, M, S) {
    .Call(`_BFL_post_pred_sample_cpp`, phi_vec, lambda_vec, pi_vec, I, C, M, S)
}

#' Modal class vote across posterior draws (Rcpp)
#'
#' @param draws Integer matrix [S x I] with values in 1..C.
#' @param C     Number of classes.
#' @return Integer vector of length I: 1-indexed modal class per observation.
#' @keywords internal
modal_class_cpp <- function(draws, C) {
    .Call(`_BFL_modal_class_cpp`, draws, C)
}
